apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-app
  template:
    metadata:
      labels:
        app: laravel-app
    spec:
      volumes:
        - name: app-code
          emptyDir: {}

      initContainers:
        - name: clone-laravel
          image: alpine/git
          args:
            [
              "clone",
              "--depth=1",
              "https://github.com/Sovanda-Mith/FinalDevOps.git",
              "/var/www/html",
            ]
          volumeMounts:
            - name: app-code
              mountPath: /var/www/html

        - name: copy-env-example
          image: alpine
          command:
            ["sh", "-c", "cp /var/www/html/.env.example /var/www/html/.env"]
          volumeMounts:
            - name: app-code
              mountPath: /var/www/html

        - name: composer-install
          image: composer:2
          workingDir: /var/www/html
          command: ["composer", "install"]
          volumeMounts:
            - name: app-code
              mountPath: /var/www/html

        - name: install-node-dependencies
          image: node:22-alpine
          workingDir: /var/www/html
          command: ["npm", "install"]
          volumeMounts:
            - name: app-code
              mountPath: /var/www/html

        - name: build-assets
          image: node:22-alpine
          workingDir: /var/www/html
          command: ["npm", "run", "build"]
          volumeMounts:
            - name: app-code
              mountPath: /var/www/html

      containers:
        - name: web
          image: richarvey/nginx-php-fpm:latest
          ports:
            - containerPort: 8080
            - containerPort: 22
          volumeMounts:
            - name: app-code
              mountPath: /var/www/html
          env:
            - name: DB_HOST
              value: 127.0.0.1
            - name: DB_DATABASE
              value: mithsovanda-db
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: Hello@123
          command: ["/bin/sh", "-c"]
          args:
            - |
              apk update && \
              apk add --no-cache openssh && \
              echo 'root:root' | chpasswd && \
              sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
              mkdir -p /run/sshd && \
              /usr/sbin/sshd && \
              cd /var/www/html && php artisan migrate --force || true && \
              exec /start.sh

        - name: mysql
          image: mysql:8.0.36
          args: ["--default-authentication-plugin=mysql_native_password"]
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: Hello@123
            - name: MYSQL_DATABASE
              value: mithsovanda-db
            - name: MYSQL_PASSWORD
              value: Hello@123
          ports:
            - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: laravel-service
spec:
  type: NodePort
  selector:
    app: laravel-app
  ports:
    - name: web
      port: 8080
      targetPort: 8080
      nodePort: 30080
    - name: ssh
      port: 22
      targetPort: 22
      nodePort: 30222
